const room00 = [];
const room01 = ['top'];
const room02 = ['right'];
const room03 = ['bottom'];
const room04 = ['left'];
const room05 = ['top', 'right'];
const room06 = ['right', 'bottom'];
const room07 = ['bottom', 'left'];
const room08 = ['left', 'top'];
const room09 = ['top', 'bottom'];
const room0a = ['right', 'left'];
const room0b = ['top', 'right', 'bottom'];
const room0c = ['right', 'bottom', 'left'];
const room0d = ['bottom', 'left', 'top '];
const room0e = ['left', 'top', 'right'];
const room0f = ['top', 'right', 'bottom', 'left'];
const rooms00_0f = [room00, room01, room02, room03, room04, room05, room06, room07, room08, room09, room0a, room0b, room0c, room0d, room0e, room0f];
window.onload = () => new Canvas(document.body, new World(16, rooms00_0f)).draw();
